import { Timestamp } from 'firebase/firestore'
import type { Tournament } from './types'

const ts = Timestamp.fromDate(new Date('2026-01-01'))

export const fallbackTournaments: Tournament[] = [
  {
    id: 'spring-ding',
    name: 'Monroeville Spring Ding',
    shortName: 'Spring Ding',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Apr 10–12',
    sport: 'Baseball',
    ages: '7u–10u',
    level: 'C, single community',
    price: 450,
    artworkUrl: '/media/2025/11/Spring-Ding.jpg',
    registrationUrl:
      'https://mbsagators.com/product/monroeville-spring-ding-april-10-april-12th/',
    status: 'closed',
    order: 1,
  },
  {
    id: 'swing-spring',
    name: 'Gators Swing into Spring',
    shortName: 'Swing into Spring',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Apr 24–26',
    sport: 'Softball & Baseball',
    ages: '7u–10u',
    level: 'C, single community',
    price: 450,
    artworkUrl: '/media/2024/04/Swing-into-Spring.jpg',
    registrationUrl:
      'https://mbsagators.com/product/monroeville-gators-swing-into-spring-april-24th-26th/',
    status: 'closed',
    order: 2,
  },
  {
    id: 'summer-swamp',
    name: 'Summer in the Swamp',
    shortName: 'Summer in the Swamp',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'May 29–31',
    sport: 'Softball & Baseball',
    ages: '8u–14u',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/04/Summer-in-the-Swamp.jpg',
    registrationUrl:
      'https://mbsagators.com/product/monroeville-summer-in-the-swamp-may-29st-31st/',
    status: 'upcoming',
    order: 3,
  },
  {
    id: 'summer-slam-1',
    name: 'Summer Slam 1.0',
    shortName: 'Summer Slam 1.0',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Jul 9–12',
    sport: 'Softball & Baseball',
    ages: '8u–14u',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/11/Summer-Slam.jpg',
    registrationUrl:
      'https://mbsagators.com/product/monroeville-summer-slam-1-0-july-9-12th/',
    status: 'upcoming',
    order: 4,
  },
  {
    id: 'summer-slam-2',
    name: 'Summer Slam 2.0',
    shortName: 'Summer Slam 2.0',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Jul 23–26',
    sport: 'Softball & Baseball',
    ages: '8u–14u',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/11/Summer-Slam.jpg',
    registrationUrl:
      'https://mbsagators.com/product/monroeville-summer-slam-2-0-july-23rd-26th/',
    status: 'upcoming',
    order: 5,
  },
  {
    id: 'beach-bash',
    name: 'Monroeville Beach Bash',
    shortName: 'Beach Bash',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Jul 30–Aug 2',
    sport: 'Softball & Baseball',
    ages: '8u–14u',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/11/Beach-Bash.jpg',
    registrationUrl:
      'https://mbsagators.com/product/monroeville-beach-bash-july-30th-august-2nd/',
    status: 'open',
    order: 6,
  },
  {
    id: 'pumpkin-smash',
    name: 'Baseball Pumpkin Smash',
    shortName: 'Pumpkin Smash',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Oct 1–4',
    sport: 'Baseball',
    ages: '8u–14u',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/11/Pumpkin-Smash.jpg',
    registrationUrl:
      'https://mbsagators.com/product/monroeville-baseball-pumpkin-smash-october-1st-4th/',
    status: 'upcoming',
    order: 7,
  },
]
