import { Timestamp } from 'firebase/firestore'
import type { Tournament } from './types'
import { combinedSportAgeFields, splitSportAgeFields } from './registrationFields'

const ts = Timestamp.fromDate(new Date('2026-01-01'))

export const fallbackTournaments: Tournament[] = [
  {
    id: 'spring-ding',
    name: 'Monroeville Spring Ding',
    shortName: 'Spring Ding',
    slug: 'monroeville-spring-ding',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Apr 10–12',
    sport: 'Baseball',
    ages: '7u–10u',
    level: 'C, single community',
    price: 450,
    artworkUrl: '/media/2025/11/Spring-Ding.jpg',
    registrationFields: splitSportAgeFields(),
    paymentRequired: true,
    status: 'closed',
    order: 1,
  },
  {
    id: 'swing-spring',
    name: 'Gators Swing into Spring',
    shortName: 'Swing into Spring',
    slug: 'swing-into-spring',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Apr 24–26',
    sport: 'Softball & Baseball',
    ages: '7u–10u',
    level: 'C, single community',
    price: 450,
    artworkUrl: '/media/2024/04/Swing-into-Spring.jpg',
    registrationFields: splitSportAgeFields(),
    paymentRequired: true,
    status: 'closed',
    order: 2,
  },
  {
    id: 'summer-swamp',
    name: 'Summer in the Swamp',
    shortName: 'Summer in the Swamp',
    slug: 'summer-in-the-swamp',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'May 29–31',
    sport: 'Softball & Baseball',
    ages: '8u–14u',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/04/Summer-in-the-Swamp.jpg',
    registrationFields: splitSportAgeFields(),
    paymentRequired: true,
    status: 'upcoming',
    order: 3,
  },
  {
    id: 'summer-slam-1',
    name: 'Monroeville Summer Slam 1.0 July 9-12th',
    shortName: 'Summer Slam 1.0',
    slug: 'summer-slam-1-0',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Jul 9–12',
    sport: 'Softball and Baseball',
    ages: '8U, 9U, 10U, 11U, 12U, *14U (softball only)',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/11/Summer-Slam.jpg',
    registrationFields: combinedSportAgeFields(),
    paymentRequired: true,
    status: 'upcoming',
    order: 4,
  },
  {
    id: 'summer-slam-2',
    name: 'Monroeville Summer Slam 2.0 July 23rd-26th',
    shortName: 'Summer Slam 2.0',
    slug: 'summer-slam-2-0',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Jul 23–26',
    sport: 'Softball and Baseball',
    ages: '8U, 9U, 10U, 11U, 12U, *14U (softball only)',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/11/Summer-Slam.jpg',
    registrationFields: combinedSportAgeFields(),
    paymentRequired: true,
    status: 'upcoming',
    order: 5,
  },
  {
    id: 'beach-bash',
    name: 'Monroeville Beach Bash July 30th-August 2nd',
    shortName: 'Beach Bash',
    slug: 'monroeville-beach-bash',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Jul 30 – Aug 2',
    sport: 'Softball and Baseball',
    ages: '8U, 9U, 10U, 11U, 12U, *14U (softball only)',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/11/Beach-Bash.jpg',
    registrationFields: splitSportAgeFields(),
    paymentRequired: true,
    status: 'open',
    order: 6,
  },
  {
    id: 'pumpkin-smash',
    name: 'Monroeville Baseball Pumpkin Smash October 1st-4th',
    shortName: 'Pumpkin Smash',
    slug: 'monroeville-baseball-pumpkin-smash',
    dateStart: ts,
    dateEnd: ts,
    dateLabel: 'Oct 1–4',
    sport: 'Softball and Baseball',
    ages: '8U, 9U, 10U, 11U, 12U, *14U (softball only)',
    level: 'B, Community',
    price: 450,
    artworkUrl: '/media/2025/11/Pumpkin-Smash.jpg',
    registrationFields: splitSportAgeFields(),
    paymentRequired: true,
    status: 'upcoming',
    order: 7,
  },
]
