import type { CalendarEvent } from './calendarEvents'

export const getInvolvedEvents: CalendarEvent[] = [
  {
    id: 0,
    title: "Spring Registration OPENS",
    start: '2024-01-01T12:00',
    end: '2024-01-01T12:00:01',
    description: '<p>Location: Website</p>',
  },
  {
    id: 1,
    title: "MBSA Sponsored Clinics",
    start: '2024-02-24T14:30',
    end: '2024-02-24T18:30:01',
    description: '<p>Location: Gateway Auxiliary Gym</p>',
  },
  {
    id: 2,
    title: "Spring Registration Deadline",
    start: '2024-02-25T00:00',
    end: '2024-02-25T00:00:01',
    description: '<p>Location: Website</p>',
  },
  {
    id: 3,
    title: "MBSA EVALUATIONS",
    start: '2024-03-02T14:30',
    end: '2024-03-02T18:30:01',
    description: '<h3>Spring 2024 Season</h3><h5>Location: Gateway Auxiliary Gym 2:30 - 6:30pm</h5><p><img class="alignnone wp-image-2492 size-full" src="/media/2024/02/Screenshot-2024-02-28-at-12.44.00 AM.png" alt="" width="1254" height="466" /></p><h5 style="text-align: left;">Our annual evaluations are here!  Time sure does fly when you’re having fun!  Please review the table above for your players division/time to report for evaluations in preparation for the upcoming draft.  This is the time where coaches will evaluate registered players to ensure we evenly distribute talent across teams to generate competitive game play throughout the season. </h5><p>Upon arrival families should “check in” at the entry desk.  Players will be given a number and then may enter the gym to begin stretching/warming up.  If you have requested your player “play up” this is an opportunity for that evaluation to occur.  Please arrive at your regularly scheduled time and let the entry personnel know you want your player to be evaluated for movement. </p><p>Head coaches will be notified shortly.  The MBSA Spring Draft will be held on Thursday, March 7th.  Additional details on the draft will come out soon to the head coaches of each division.  The drafts for softball will be led by MBSA Softball Commissioner, Jeff Kovacs, and baseball will be overseen by MBSA Executive Commissioner, Josh Plassmeyer.   If anyone has any questions regarding the drafts please email us at<span style="color: #0000ff;"> </span><a href="mailto:softball@mbsagators.com" target="_blank" rel="noopener"><span style="color: #0000ff;">softball@mbsagators.com</span></a> or <a href="mailto:commissioner@mbsagators.com" target="_blank" rel="noopener"><span style="color: #0000ff;">commissioner@mbsagators.com</span></a>. </p><p><span style="color: #ff0000;">Softball Announcement</span> - We will have special guests assisting with our evaluations on Saturday.  The Gateway High School softball team will join us to help run our drills! </p><p><span style="color: #ff0000;">Instructional and 6U Softball Families</span> - will have a standard clinic and not have official evaluations for these age groups.<br /><u><br /><span style="color: #ff0000;">Coaches for both leagues should attend their designated session for evaluations.  If you are unable to make it please let the corresponding commissioner know in advance.  Players are not required but it is highly recommended that they attend so that we can properly balance the teams during our draft night on March 7<sup>th</sup>.</span></u></p><p>All coaches should confirm that MBSA has clearances in place prior to starting practice in March.  Please follow the link below to get those documents started as some take a little time to come in.  Once the certificates are received please email them to <a href="mailto:info@mbsagators.com" target="_blank" rel="noopener"><span style="color: #0000ff;">info@mbsagators.com</span></a>.</p><h5 style="text-align: left;" align="center"><span style="color: #0000ff;"><a style="color: #0000ff;" href="https://mbsagators.com/coaches/" target="_blank" rel="noopener" data-saferedirecturl="https://www.google.com/url?q=https://mbsagators.com/coaches/&amp;source=gmail&amp;ust=1709213233247000&amp;usg=AOvVaw11Aj3J31FvoeReEc35dFG1">https://mbsagators.com/<wbr />coaches</a></span></h5><h5 style="text-align: left;" align="center">Please keep an eye on your emails!  Make sure that our account is set to not be forwarded to junk or spam folders!  This is our most effective form of communication!  The website will be updated regularly with any new information, but emails are the best and most timely source of information! </h5><p>We look forward to amazing start of our Spring Season!  Go Gators!</p><p>See you on the fields,</p><h5 style="text-align: left;"> </h5><h5 style="text-align: left;">MBSA Board of Directors</h5>',
  },
  {
    id: 4,
    title: "MBSA Draft",
    start: '2024-03-07T18:30',
    end: '2024-03-07T18:30:01',
    description: '<p>Location: Papa Rocks</p>',
  },
  {
    id: 5,
    title: "Baseball and Softball Clinic",
    start: '2024-03-09T14:30',
    end: '2024-03-09T18:30:01',
    description: '<h3>Spring 2024 Season</h3><h5>Location: Gateway Auxiliary Gym 2:30 - 6:30pm</h5><p><img class="alignnone wp-image-2589 size-full" src="/media/2024/03/Screenshot-2024-03-05-at-12.38.48 PM.png" alt="" width="1250" height="356" /></p><h5><b>Registration for each clinic can be found on our website <a href="http://www.mbsagators.com/" target="_blank" rel="noopener" data-saferedirecturl="https://www.google.com/url?q=http://www.mbsagators.com&amp;source=gmail&amp;ust=1709746470567000&amp;usg=AOvVaw1WB96mOgyY_UEJGnDVLJKE">www.mbsagators.com</a>. Log into your account and select the registration that you will be attending.</b></h5><h5><b>Instructional Baseball (T-ball) and Softball(6U) Clinic:</b></h5><ul><li>Perfect clinics for all players registered at the instructional age level (4-6).</li><li>Sarah Cunningham our Instructional League Commissioner will lead the charge with some excellent drills for our young athletes!</li></ul><h5><b>Softball Clinic – Base Running and Fundamentals:</b></h5><ul><li>We encourage all to attend however this clinic will be geared toward those that want a little extra work on understanding quality base running technique and fundamentals.</li><li>This clinic will be led by our Softball Commissioner Jeff Kovacs</li></ul><ul><li><b>Baseball – All Skills Clinic</b></li><li>Those that register for this clinic (7U-12U) will get a great experience in all facets of the sport. Baserunning, defending, hitting drills, and pitching (9U-12U) will all be reviewed using different stations.</li><li>Executive Commissioner Josh Plassmeyer will lead this experience.</li></ul><h5 style="text-align: left;"> <u>COACHES ARE NEEDED!</u></h5><ul><li><p>We are short coaches at the Bronco, Coach Pitch and Instructional T-ball level. The draft is scheduled for March 7<sup>th</sup></p></li><li>1 needed at Bronco (11-12 yrs old)</li></ul><ul><li>2 needed at Coach Pitch (7-8 yrs old)</li></ul><ul><li>2 needed at Instructional T-ball (4-6 yrs old)</li></ul><p>Volunteer coaching is so vital to the success of our program and creating memorable, safe and education experiences for all of our players and families. We will push through for the Spring season however, if coaches are not secured teams may be overpopulated which will lead to decreased playing time for all players, higher player to coach ratios, and overall, less of an experience. We urge anyone that has a desire to coach to let us know ASAP!  Not to mention you get a FREE REGISTRATION and more perks out of it!</p><p>Here are a couple options to consider:</p><ol><li>Co-Head Coaches – team up with a couple assistants to help manage the team together</li><li>Tournament Assistant Coaches – we urge you to head coach during our spring and fall seasons!</li></ol><h5><b><u>Clearances</u></b></h5><p>All coaches (head and assistant) should confirm that MBSA has clearances in place prior to starting practice in March.Please follow the link below to get those documents started as some take a little time to come in. Once the certificates are received please email them to <a href="mailto:info@mbsagators.com" target="_blank" rel="noopener">info@mbsagators.com</a>.</p><p><a href="https://mbsagators.com/coaches/" target="_blank" rel="noopener" data-saferedirecturl="https://www.google.com/url?q=https://mbsagators.com/coaches/&amp;source=gmail&amp;ust=1709746470567000&amp;usg=AOvVaw1kdnOJNtxRV0TNlIMgMTwy">https://mbsagators.com/<wbr />coaches/</a></p><h5><b><u>Read Your Emails!</u></b></h5><p>Please keep an eye on your emails! Make sure that our account is set to not be forwarded to junk or spam folders! This is our most effective form of communication! The website will be updated regularly with any new information, but emails are the best and most timely way to get you all the information!</p><p>We look forward to amazing start of our Spring Season! Go Gators!</p><p>See you on the fields,</p><p>MBSA Board of Directors</p>',
  },
  {
    id: 6,
    title: "Baseball and Softball Clinic",
    start: '2024-03-16T14:30',
    end: '2024-03-16T18:30:01',
    description: '<p><strong>Coaches "Clinic" and Tutorial</strong></p><p>The Commissioners of MBSA, Josh Plassmeyer and Jeff Kovacs, will be hosting a Coaches Expectations and GameChanger Tutorial Session during each of the times noted below.  We HIGHLY encourage all coaches both Head and Assistant to attend.   During this session Jeff will review the basic of GameChanger as all teams must use this app moving forward for management of teams.  Josh and Jeff will review the Coaches Expectations as we begin our spring season.  This will include review of how best to approach Spring practices, planning, and much more.  Jeff will show the ins and outs of player entry, game score keeping, and messaging basics during this time.</p><p>We are excited to announce the return of our <strong>Speed and Agility clinic with GAMA /Forza Sports &amp; Performance Training</strong>.</p><p><u>When:</u>  Saturday March 16th</p><p><u>Where:</u> Gateway High School Auxiliary Gym</p><p><u>Times:</u>        3:30 - 4:30pm - 7-8 year olds</p><p>                   4:30 - 5:30pm - 9-10 year olds</p><p>                   5:30 - 6:30pm - 11-14 year olds</p><p>These clinics are co-ed and designed to help everyone learn basic skills and drills to improve their speed and agility and safety while playing sports.</p><p>GAMA and Forza Sports and Performance Training has been a very strong partner of MBSA since we first started last year.  They have offered field time, clinics, assessments, etc to our organization. We really appreciate their will and drive to mirror our goal of getting the youth of MBSA active and on the fields!</p><p><u>Instructional T-ball and 6U Clinic</u></p><p>Our regularly scheduled Instructional Clinic will continue at the Gateway High School Auxiliary Gym from 2:30-3:30 on March 16th too!</p><p>Registration for both events can be found on our website: <a href="http://www.mbsagators.com/" target="_blank" rel="noopener" data-saferedirecturl="https://www.google.com/url?q=http://www.mbsagators.com&amp;source=gmail&amp;ust=1710177412492000&amp;usg=AOvVaw3_4Csody_2KDazQxlv0B49">www.mbsagators.com</a>.</p><p>See you on the fields,</p><p>MBSA Board of Directors</p>',
  },
  {
    id: 7,
    title: "MBSA Sponsored Clinics",
    start: '2024-03-23T14:30',
    end: '2024-03-23T18:30:01',
    description: '<p>Location: Gateway Auxiliary Gym</p>',
  },
  {
    id: 8,
    title: "MBSA Sponsored Clinics",
    start: '2024-03-30T14:30',
    end: '2024-03-30T18:30:01',
    description: '<p>Location: Gateway Auxiliary Gym</p>',
  },
  {
    id: 9,
    title: "MPW/E Opens for MBSA Practice Use",
    start: '2024-04-01',
    end: '2024-04-02',
    description: '<p>Location: MPW/E</p>',
  },
  {
    id: 10,
    title: "MBSA Spring Baseball Tournament",
    start: '2024-04-12',
    end: '2024-04-15',
    description: '<p>Location: MPW</p><p>Time: TBD</p>',
  },
  {
    id: 11,
    title: "2024 Fall Ball Registration",
    start: '2024-07-01',
    end: '2024-07-02',
    description: '<p>The <span class="il">MBSA</span> Board of Directors has decided to open Fall Ball registration a little earlier than normal.  This year we will be offering a package deal!  You will be able to register for the Fall 2024 <strong>AND </strong>Spring 2025 season at a discounted rate if you so choose.  We encourage all families to register in advance so that our planning can be done for the upcoming season.</p><p>FALL BALL DETAILS:<a id="m_7991091948191504242dnn_ctr758057_BulkEmail_btnSendNow"></a> Send Now                             </p><p><strong>Registration Opens: </strong>      July 1, 2024<br /><strong>Fall Only Registration:       </strong>  $55.00 <br /><strong>Fall + Spring Registration:</strong>  $120.00 ($10 discount)</p><p>Multiplayer discounts will apply as well. <br />Scholarship can be made available to those that need them by emailing <a href="mailto:commissioner@mbsagators.com" target="_blank" rel="noopener">commissioner@mbsagators.com</a>.</p><p><strong>REGISTRATION WILL CLOSE ON August 4th at Midnight!</strong></p><p>PLEASE DO NOT WAIT UNTIL THE LAST SECOND TO REGISTER!</p>',
  },
  {
    id: 12,
    title: "Haylie Brunson Registration",
    start: '2024-07-01',
    end: '2024-07-02',
    description: '<p><strong>2024 Haylie Brunson - Tournament Softball Clinic Series</strong></p><p><span class="il">MBSA</span> is offering another great opportunity for our softball players thanks to our amazing Softball Commissioner, Jeff Kovacs.  Through a continued partnership with Haylie Brunson, now Penn State Softball Player, we are able to offer a 3 day clinic that will be specific to certain positions including batting, pitching/catching, and fielding.  Details about the clinic are below and attached in the flyer.</p><p>If your player is rostered on a current <span class="il">MBSA</span> Tournament Softball Team you are eligible.  </p><p><strong>Registration Opens: </strong>      July 1, 2024<br /><strong>Clinic Only Registration (per clinic day):  </strong>   $50.00</p><p><strong>If you register for Fall Ball as well a clinic day the cost will drop to $25.00.  That a 50% discount with a Fall Ball Registration too!  </strong></p><p><strong>Clinic Dates:  </strong>July 16 (batting), July 17 (pitching/catching), and July 18th (infield/outfield)<strong><br />Clinic Time:  </strong>8:30-11:30 am<strong><br />Clinic Location:  </strong>Monroeville Park West Fields</p><p>As a point of clarity, each clinic day is $50.  However, if you register for Fall Ball 2024 the clinic rate drops to $25 per day!  We hope to see you other there!!!!!!!!!</p><p>Additional Softball Clinics for our non-tournament players will be held later this summer/fall.  We are working with the Gateway HS team to establish some dates and times!</p><p>If anyone has any questions please reach out to <a href="mailto:info@mbsagators.com" target="_blank" rel="noopener">info@mbsagators.com</a> and we will be happy to answer any questions.</p>',
  },
  {
    id: 13,
    title: "4th of July Parade",
    start: '2024-07-04',
    end: '2024-07-05',
    description: '<p><span class="il">MBSA</span> has secured a spot in the Monroeville 4th of July Parade.  This is open to any and all <span class="il">MBSA</span> Players and Families.  The registration to sign up for this is located on our website and is OPEN NOW!!!.  <span style="color: #0000ff;"><a style="color: #0000ff;" href="https://login.stacksports.com/login?client_id=612b0399b1854a002e427f78&amp;redirect_uri=https://core-api.bluesombrero.com/login/redirect/portal/9011&amp;app_name=Monroeville+Baseball+Association&amp;portalid=9011&amp;instancekey=leagues" target="_blank" rel="noopener">Log into your account</a></span> and select it from the available programs. </p><p><span class="il">MBSA</span> will hold slot 33 in the parade and likely meet somewhere near Chic-Fil-A at around 8:30am.  Participants are encouraged to wear your <span class="il">MBSA</span> Jersey and bring a bag of candy to throw to spectators when walking!  </p>',
  },
  {
    id: 14,
    title: "TEAM PICTURE DAY",
    start: '2024-04-20',
    end: '2024-04-21',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 15,
    title: "2024 Opening Day",
    start: '2024-04-27T10:00',
    end: '2024-04-27T20:00:01',
    description: '<p>Hello MBSA Families,</p><p><b><u>OPENING DAY IS SATURDAY, APRIL 27<sup>th</sup>!!!</u></b></p><p><b>We are excited to announce that we have are LARGEST ever MBSA League. </b></p><p><b>9 a.m.</b> -- Player drops off at the Gazebo. Josh Plassmeyer, MBSA Executive Commissioner, will assist in arranging the teams in order by age group and coach\'s last name. Players should start to arrive at the field and begin to congregate in the grass field in front of the gazebo near the entrance roads of the park.  Coach Josh will then be around to line everyone up.   Parents, please wait until your head coach has arrived before departing to line up for the parade!</p><p><b>10 a.m.</b> – The parade will start at the Gazebo. Parents are encouraged to line up along the route from the gazebo to the fields to take pictures and wave to our teams and coaches!</p><p><b>11 p.m.</b> -- Welcome ceremony, led by our President José Rodriguez, where teams and Opening Day Sponsors, will be introduced.  Coach Jose will be sharing our accomplishments this offseason as well as important information about 2024 and beyond, followed by our First Pitch Ceremony to kick off the day!</p><p><b>12 p.m.</b> – GAMES Start!</p><p>Opening Day will have lots of activities for our families and visitors!  Face painting, craft vendors, Italian ice, balloon artists and more!  We’ve revamped our concessions operation, which will be open the entire day too!</p><p>We would like to thank Michelle Kilburn and the Opening Day Committee for all of their hard work organizing an amazing day for all of our families!</p><p><b><u>MBSA Equipment Donation and “Swap and Shop”</u></b></p><p>MBSA’s Equipment Manager, Anthony Yarkowski, will be set up at MPW by the equipment shed behind Field 4 from 12-2 to accept donations of used softball and baseball gear and equipment. Our “Swap &amp; Shop” will continue during the same time and at the same location for <b><u>ALL</u></b> MBSA families whether you donated or not.  If you need equipment, please stop by and see Anthony or his designee when he’s out there coaching!!!! MBSA is committed to helping any way we can!</p><p><b><u>FAN GEAR</u></b></p><p>You will be able to purchase fan gear on opening day!  We will be selling adult and youth size t-shirts as well as women’s tank tops (while supplies last). MBSA’s Uniform and Sponsor Vice President, Mehdi Hedjazi, will lead the table selling these!  Be sure to check them out!  </p><p><b><u>Concession Upgrades</u></b></p><p>MBSA\'s Concessions Manager, Nia Graziano, has changed our concession stand operations significantly with new menu items and superior upgrades!  Remember our stand accepts cash or card transactions all day long!  Oh by the way... it has a new name too!! Make sure you visit the SWAMP SHACK for all your concession needs this season!!  </p><p><b><u>MBSA Picture Make Up Day</u></b></p><p>Sunday, April 28<sup>th</sup> from 11am-1pm at MPW Field 1.  Make up day will be for anyone who was not able to attend the originally scheduled picture day.  Please show up picture ready.  The process should not take more than a couple minutes per kid.  Please reach out to our MBSA Executive Commissioner if you have any questions at <a href="mailto:commissioner@mbsagators.com" target="_blank" rel="noopener">commissioner@mbsagators.com</a></p><p>We hope to see you there! Feel free to reach out to <a href="mailto:info@mbsagators.com" target="_blank" rel="noopener">info@mbsagators.com</a><u> </u>with any questions!</p><p>See you at the fields!</p><p>MBSA Board of Directors</p>',
  },
  {
    id: 16,
    title: "2024 Opening Day Make Up Picture Day",
    start: '2024-04-27',
    end: '2024-04-28',
    description: '<p>Location: MPW</p><p>Time: TBD</p>',
  },
  {
    id: 17,
    title: "Picture Day",
    start: '2024-04-21',
    end: '2024-04-22',
    description: '<p>Hello MBSA Family!</p><p>Please see below for important information regarding picture day scheduled for Sunday, April 21st (head coaches have your time slot) and make up day on Sunday, April 28th (Time TBD).</p><p>Dear Parents &amp; Coaches: <br /><u></u><u></u></p><p>Picture day is scheduled for April 21st at Monroeville Park West - Field 1.  Your coach will have your scheduled time. <u></u><u></u></p><p><b>Please bring your bat and glove for photos! <u></u><u></u></b></p><p>Here are INSTRUCTIONS FOR ORDERING YOUR PHOTOS FROM TSS PHOTOGRAPHY.</p><p>Every athlete will have at least 2-3 poses taken.  <b>We are doing Virtual groups so if you cannot make your scheduled time, please come anytime between 9:00 am – 3:00 pm.  You will still be in the team photo.  please make every effort to come on the 21<sup>st</sup>.  There will only be a makeup day if we get enough participants to commit to a makeup session on April 28th but the primary day is preferred.  </b></p><p>We will have rosters on hand so you <u>do NOT need to turn anything in on picture day</u>!  No money or package selections are collected on picture day.</p><p>After picture day, you will then receive an email telling you that the photos are ready to view.  (about one week after picture day)   The email will include a link to the photos.  (Check your junk mail in case it ends up there.  Gmail send many of our emails to junk because we include a link to your photos)</p><p>If you do not receive an email, go to <a href="https://urldefense.com/v3/__http:/www.tssorders.com__;!!NHLzug!Kl3p9y2j9pPxC63sfvXvPq4QJhpBb9Nat59JNXHF_5WdRtKmvDgA1wqkwNvv3LXG5jfppqDethYHdC06IZP3uW6nIZ-bYg$" target="_blank" rel="noopener" data-saferedirecturl="https://www.google.com/url?q=https://urldefense.com/v3/__http:/www.tssorders.com__;!!NHLzug!Kl3p9y2j9pPxC63sfvXvPq4QJhpBb9Nat59JNXHF_5WdRtKmvDgA1wqkwNvv3LXG5jfppqDethYHdC06IZP3uW6nIZ-bYg$&amp;source=gmail&amp;ust=1713662635945000&amp;usg=AOvVaw0qJaTA6r8LvLEFMOaPtrmj">www.tssorders.com</a><u></u><u></u></p><p>Enter the event number 27233598 and search by last name. </p><p>Our state of the art website will allow you to view the photos before you order.  All photos/products will be shipped directly to you!  You can order as many poses as you choose! <u></u><u></u></p><p>We will give everyone 30 days to place your initial order.  We have a very fast turnaround. </p><p><b>Please call or email TSS Photography directly with any questions!  </b></p><p>412-344-3100</p><p><a href="mailto:tsspittsburgh@gmail.com" target="_blank" rel="noopener">tsspittsburgh@gmail.com</a></p><p>See you at the fields,</p><p>Josh Plassmeyer<br />MBSA Executive Commissioner </p>',
  },
  {
    id: 18,
    title: "Make Up Picture Day",
    start: '2024-04-28',
    end: '2024-04-29',
    description: '<p>Hello MBSA Family!</p><p>Please see below for important information regarding make up picture day scheduled on Sunday, April 28th (Time TBD).</p><p>Dear Parents &amp; Coaches: <u></u><u></u></p><p><b>Please bring your bat and glove for photos! <u></u><u></u></b></p><p>Here are INSTRUCTIONS FOR ORDERING YOUR PHOTOS FROM TSS PHOTOGRAPHY.</p><p>Every athlete will have at least 2-3 poses taken.  <b>We are doing Virtual groups so if you cannot make your scheduled time, please come anytime between 9:00 am – 3:00 pm.  You will still be in the team photo.  please make every effort to come on the 21<sup>st</sup>.  There will only be a makeup day if we get enough participants to commit to a makeup session on April 28th but the primary day is preferred.  </b></p><p>We will have rosters on hand so you <u>do NOT need to turn anything in on picture day</u>!  No money or package selections are collected on picture day.</p><p>After picture day, you will then receive an email telling you that the photos are ready to view.  (about one week after picture day)   The email will include a link to the photos.  (Check your junk mail in case it ends up there.  Gmail send many of our emails to junk because we include a link to your photos)</p><p>If you do not receive an email, go to <a href="https://urldefense.com/v3/__http:/www.tssorders.com__;!!NHLzug!Kl3p9y2j9pPxC63sfvXvPq4QJhpBb9Nat59JNXHF_5WdRtKmvDgA1wqkwNvv3LXG5jfppqDethYHdC06IZP3uW6nIZ-bYg$" target="_blank" rel="noopener" data-saferedirecturl="https://www.google.com/url?q=https://urldefense.com/v3/__http:/www.tssorders.com__;!!NHLzug!Kl3p9y2j9pPxC63sfvXvPq4QJhpBb9Nat59JNXHF_5WdRtKmvDgA1wqkwNvv3LXG5jfppqDethYHdC06IZP3uW6nIZ-bYg$&amp;source=gmail&amp;ust=1713662635945000&amp;usg=AOvVaw0qJaTA6r8LvLEFMOaPtrmj">www.tssorders.com</a><u></u><u></u></p><p>Enter the event number 27233598 and search by last name. </p><p>Our state of the art website will allow you to view the photos before you order.  All photos/products will be shipped directly to you!  You can order as many poses as you choose! <u></u><u></u></p><p>We will give everyone 30 days to place your initial order.  We have a very fast turnaround. </p><p><b>Please call or email TSS Photography directly with any questions!  </b></p><p>412-344-3100</p><p><a href="mailto:tsspittsburgh@gmail.com" target="_blank" rel="noopener">tsspittsburgh@gmail.com</a></p><p>See you at the fields,</p><p>Josh Plassmeyer<br />MBSA Executive Commissioner </p>',
  },
  {
    id: 19,
    title: "ACB/S Tournament",
    start: '2024-05-04',
    end: '2024-05-06',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 20,
    title: "ACB/S Tournament",
    start: '2024-05-10',
    end: '2024-05-13',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 21,
    title: "ALL Star Day",
    start: '2024-05-19',
    end: '2024-05-20',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 22,
    title: "ACB/S Tournament",
    start: '2024-05-25',
    end: '2024-05-28',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 23,
    title: "MBSA Softball Tournament (8U, 10U, 12U)   \u201cSummer in the Swamp\u201d",
    start: '2024-05-31',
    end: '2024-06-03',
    description: '<p>Location: MPW</p><p>Time: TBD</p>',
  },
  {
    id: 24,
    title: "ACB/S Tournament",
    start: '2024-06-07',
    end: '2024-06-10',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 25,
    title: "TBD League CHAMPIONSHIP WEEK",
    start: '2024-06-10',
    end: '2024-06-14',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 26,
    title: "TBD League CHAMPIONSHIP WEEK",
    start: '2024-06-17',
    end: '2024-06-20',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 27,
    title: "ACB/S Tournament",
    start: '2024-06-14',
    end: '2024-06-17',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 28,
    title: "ACB/S Tournament",
    start: '2024-06-20',
    end: '2024-06-24',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 29,
    title: "MBSA Baseball Tournament  (12U, 11U, 9U) \u201cMBSA Baseball Bash\u201d",
    start: '2024-07-12',
    end: '2024-07-15',
    description: '<p>Location: MPW</p><p>Time: TBD</p>',
  },
  {
    id: 30,
    title: "Haylie Brunson Clinic ",
    start: '2024-07-16',
    end: '2024-07-17',
    description: '<p><img class="alignnone size-medium wp-image-2874" src="/media/2024/07/July-Softball-Clinic-300x300.jpg" alt="" width="300" height="300" /></p><p>Location: MPW</p><p>Time: 8:30 - 11:30</p><p>CLINIC FOCUS WILL BE BATTING.</p><p>OPEN TO ALL MBSA TOURNEY SOFTBALL<br />PLAYERS 9U AND OLDER</p>',
  },
  {
    id: 31,
    title: "Haylie Brunson Clinic ",
    start: '2024-07-17',
    end: '2024-07-18',
    description: '<p><img class="alignnone size-medium wp-image-2874" src="/media/2024/07/July-Softball-Clinic-300x300.jpg" alt="" width="300" height="300" /></p><p>Location: MPW</p><p>Time: 8:30 - 11:30</p><p>CLINIC FOCUS WILL BE PITCHING/CATCHING.</p><p>OPEN TO ALL MBSA TOURNEY SOFTBALL<br />PLAYERS 9U AND OLDER</p>',
  },
  {
    id: 32,
    title: "Haylie Brunson Clinic ",
    start: '2024-07-18',
    end: '2024-07-19',
    description: '<p><img class="alignnone size-medium wp-image-2874" src="/media/2024/07/July-Softball-Clinic-300x300.jpg" alt="" width="300" height="300" /></p><p>Location: MPW</p><p>Time: 8:30 - 11:30</p><p>CLINIC FOCUS WILL BE INFIELD/OUTFIELD.</p><p>OPEN TO ALL MBSA TOURNEY SOFTBALL<br />PLAYERS 9U AND OLDER</p>',
  },
  {
    id: 33,
    title: "ACB/S Tournament",
    start: '2024-07-18',
    end: '2024-07-22',
    description: '<p>Location: MPW</p>',
  },
  {
    id: 34,
    title: "MBSA Baseball Tournament  (7U, 8U, 10U) \u201cMBSA Baseball Bash\u201d",
    start: '2024-07-26',
    end: '2024-07-29',
    description: '<p>Location: MPW</p><p>Time: TBD</p>',
  },
  {
    id: 35,
    title: "MBSA Softball Classic (8U, 10U, 12U) ",
    start: '2024-08-02',
    end: '2024-08-05',
    description: '<p>Location: MPW</p><p>Time: TBD</p>',
  },
  {
    id: 36,
    title: "2025 Spring Registration Closes",
    start: '2025-02-23T12:00',
    end: '2024-11-24T12:00:01',
  },
  {
    id: 37,
    title: "MBSA Player Evaluations",
    start: '2025-03-01T16:00',
    end: '2024-11-11T18:00:01',
  },
  {
    id: 38,
    title: "MBSA Player Evaluations",
    start: '2025-03-02T10:00',
    end: '2025-03-02T15:00:01',
  },
  {
    id: 39,
    title: "2025 Picture Day",
    start: '2025-04-26',
    end: '2026-06-29',
  },
  {
    id: 40,
    title: "Opening Day 2025",
    start: '2025-04-26T10:00',
    end: '2025-04-26T20:00:01',
  },
  {
    id: 41,
    title: "2025 Picture Make Up Day",
    start: '2025-04-27',
    end: '2026-06-29',
  },
  {
    id: 42,
    title: "Spring Registration Deadline",
    start: '2025-02-23T12:00',
    end: '2025-02-23T12:00:01',
  },
  {
    id: 43,
    title: "MBSA Evaluations 12U Softball",
    start: '2025-02-28T18:00',
    end: '2025-02-28T20:15:01',
    description: '<p>Gateway Auxiliary Gym</p>',
  },
  {
    id: 44,
    title: "MBSA Evaluations Mustang",
    start: '2025-03-01T10:30',
    end: '2025-02-01T12:30:01',
    description: '<p>Gateway Auxiliary Gym</p>',
  },
  {
    id: 45,
    title: "MBSA Evaluations Coach Pitch",
    start: '2025-03-01T15:00',
    end: '2025-03-01T17:00:01',
    description: '<p>All American Trafford</p>',
  },
  {
    id: 46,
    title: "MBSA Evaluations 8U Softball",
    start: '2025-03-02T10:30',
    end: '2025-03-02T12:30:01',
    description: '<p>All American Trafford</p>',
  },
  {
    id: 47,
    title: "MBSA Evaluations 10U Softball",
    start: '2025-03-02T12:30',
    end: '2025-03-02T14:30:01',
    description: '<p>Gateway Auxiliary Gym</p>',
  },
  {
    id: 48,
    title: "MBSA Evaluations Bronco",
    start: '2025-03-02T15:00',
    end: '2025-03-02T17:00:01',
    description: '<p>All America Trafford</p>',
  },
  {
    id: 49,
    title: "MBSA Softball Draft",
    start: '2025-03-04T18:00',
    end: '2026-06-28T00:00:01',
    description: '<p>Coxcomb</p>',
  },
  {
    id: 50,
    title: "MBSA Baseball Draft",
    start: '2025-03-06T18:00',
    end: '2026-06-28T00:00:01',
    description: '<p>Papa Rocks</p>',
  },
  {
    id: 51,
    title: "Submit Any Uniform Changes",
    start: '2025-03-09T12:00',
    end: '2026-06-28T00:00:01',
  },
  {
    id: 52,
    title: "Organize Uniforms for Submission",
    start: '2025-03-10T12:00',
    end: '2026-06-28T00:00:01',
  },
  {
    id: 53,
    title: "MBSA Team Practices can begin on dirt fields",
    start: '2025-03-10T12:00',
    end: '2026-06-28T00:00:01',
    description: '<p>Monroeville</p>',
  },
  {
    id: 54,
    title: "Submit Uniform to Artex",
    start: '2025-03-11T12:00',
    end: '2026-06-28T00:00:01',
  },
  {
    id: 55,
    title: "MPW/E Opens for MBSA Practice Use",
    start: '2025-04-01',
    end: '2026-06-29',
    description: '<p>MPW/E</p>',
  },
  {
    id: 56,
    title: "MBSA Tournament \"Spring Ding\" OPEN",
    start: '2025-04-12T12:00',
    end: '2025-04-14T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 57,
    title: "2025 MBSA Opening Day ",
    start: '2025-04-26T10:00',
    end: '2026-06-28T00:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 58,
    title: "TEAM PICTURE DAY",
    start: '2025-04-26T10:00',
    end: '2026-06-28T00:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 59,
    title: "2025 Make Up Picture Day",
    start: '2025-04-27T10:00',
    end: '2026-06-28T00:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 60,
    title: "ACB/S Tournament",
    start: '2025-05-03T12:00',
    end: '2025-05-04T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 61,
    title: "ACB/S Tournament",
    start: '2025-05-09T12:00',
    end: '2025-05-11T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 62,
    title: "ACB/S Tournament",
    start: '2025-05-09T12:00',
    end: '2025-05-11T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 63,
    title: "ACB/S Tournament",
    start: '2025-05-24T12:00',
    end: '2025-05-26T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 64,
    title: "MBSA Tournament \u201cSummer in the Swamp\u201d OPEN",
    start: '2025-06-06T12:00',
    end: '2025-06-08T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 65,
    title: "ACB/S Tournament",
    start: '2025-05-24T12:00',
    end: '2025-05-26T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 66,
    title: "MBSA Instructional and 6U Championships",
    start: '2025-06-02T12:00',
    end: '2025-06-05T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 67,
    title: "8U/10U, Coach Pitch",
    start: '2025-06-09T12:00',
    end: '2025-06-12T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 68,
    title: "Mustang/Bronco/12U",
    start: '2025-06-16T12:00',
    end: '2025-06-18T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 69,
    title: "ACB/S Tournament",
    start: '2025-06-13T12:00',
    end: '2025-06-15T12:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 70,
    title: "ACB/S Tournament",
    start: '2025-06-19T12:00',
    end: '2025-06-22T13:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 71,
    title: "MBSA All Star Nights",
    start: '2025-06-23T18:00',
    end: '2025-06-24T21:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 72,
    title: "ACB/S Tournament",
    start: '2025-06-27T12:00',
    end: '2025-06-29T13:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 73,
    title: "MBSA Tournament  \u201cMBSA Summer Slam\u201d",
    start: '2025-07-11T12:00',
    end: '2025-07-13T13:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 74,
    title: "ACB/S Tournament",
    start: '2025-07-17T12:00',
    end: '2025-07-20T13:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 75,
    title: "MBSA Tournament  \u201cMBSA Summer Slam\u201d",
    start: '2025-07-25T12:00',
    end: '2025-07-27T13:00:01',
    description: '<p>MPW</p>',
  },
  {
    id: 76,
    title: "MBSA Tournament \u201cMBSA Beach Bash\u201d",
    start: '2025-08-01T12:00',
    end: '2025-08-03T13:00:01',
    description: '<p>MPW</p>',
  },
]
